theme = "DoIt"
baseURL = 'https://artexxx.github.io/'
languageCode = "en"
languageName = "English"
hasCJKLanguage = false
defaultContentLanguage = "en"
title = 'artexxx.github.io'
copyright = "Artexxx"
timeZone = "Australia/Melbourne"

# Code Highlight
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10
summaryLength = 100
enableRobotsTXT = true
# relativeURLs = true

enableGitInfo = true
enableEmoji = true
enableInlineShortcodes = true

fontFamily = "Atkinson Hyperlegible"
titleFontFamily = "Atkinson Hyperlegible"

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'Box'

[[menu.main]]
  identifier = "posts"
  # you can add extra information before the name (HTML format is supported), such as icons
  # pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  # post = ""
  name = "📝 Posts"
  url = "/posts/"
  # title will be shown when you hover on this menu link
  # title = ""
  weight = 1
[[menu.main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "🍱 Categories"
  url = "/categories/"
  title = ""
  weight = 3
[[menu.main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "📚 Series"
  url = "/series/"
  title = ""
  weight = 4
[[menu.main]]
  identifier = "links"
  pre = ""
  post = ""
  name = "🔗 Links"
  url = "/links/"
  title = "Links to software and services I use"
  weight = 5
[[menu.main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "🤦🏻‍♂️ About"
  url = "/about/"
  title = "Sam McLeod"
  weight = 6

[permalinks]
  posts = "/:year/:month/:slug/"
  page = "/:slug/"



[params]
  author = "Artexx"
	subtitle = "The personal blog of Artexx"

  # logo = "/logo.svg"
  # favicon = "/favicon.png"  # 32x32
  # faviconIco = "/favicon.ico"  # 32x32
  # appletouch = "/apple-touch-icon.png"  # 180x180
  # svgicon = "/logo.svg"
  # icon512 = "/icon512.png"  # 512x512 png

  # DoIt theme settings
  defaultTheme = "auto"
  version = "0.2.X"
  fingerprint = "" # sha512
  gitRepo = "https://github.com/Artexxx"
  # keywords = ["Artexx", "sammcj", "smcleod", "s_mcleod", "devops", "tech", "engineering"]
  # images = ["/apple-touch-icon.png", "/profilephoto/apple-touch-icon.png"]

  # enablePWA = true

  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    # gravatarEmail = ""
    # URL of avatar shown in home page
## avatarURL = "/profilephoto/logo.svg"
## images = ["/apple-touch-icon.png", "/profilephoto/apple-touch-icon.png"]
    # title = "smcleod.net"
    subtitle = "The personal blog of Artexxx"
    # subtitle shown in home page
    # subtitle = "This is My New Hugo Site"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # disclaimer = "Words are my own or somebody else's 🖖🏼"
  # Home page posts
  [params.home.posts]
    enable = true
    paginate = 10

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Artexxx blog"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    # svgFavicon = "/logo.svg"
    # Safari mask icon color
    # iconColor = "#5bbad5"
    # Windows v8-10 tile color
    # tileColor = "#da532c"


  # Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 200
    # date format (month and day)
    dateFormat = "Jan-01"
    # amount of RSS pages
    rss = 10
    # recently updated posts settings
    [params.section.recentlyUpdated]
      enable = false
      rss = true
      days = 30
      maxCount = 5


  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia", "fuse")
    type = "fuse"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # DoIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # DoIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # DoIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # DoIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.fuse]
      # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = true
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = true
      ignoreFieldNorm = false

  [params.page]
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # linkToEdit = "https://github.com/sammcj/smcleod/edit/main/content/{path}"

    # whether to enable series navigation
    seriesNavigation = true

    [params.page.code]
      copy = true
      maxShownLines = 100

    [params.page.comment]
      enable = true
      [params.page.comment.giscus]
        enable = true
        dataRepo = "Artexxx/Artexxx.github.io"
        dataRepoId = "R_kgDOK_NUFQ"
        dataCategory = "Announcements"
        dataCategoryId = "DIC_kwDOK_NUFc4CcHDw"
        dataMapping = "pathname"
        dataStrict = "0"
        dataReactionsEnabled = "1"
        dataEmitMetadata = "0"
        dataInputPosition = "bottom"
        crossorigin = "anonymous"
        lightTheme = "light"
        darkTheme = "dark"
        dataLang = "en"

    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      #  whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = false

    [params.page.related]
      enable = true
      count = 5

    [params.page.header]
      # whether to enable auto header numbering
      [params.page.header.number]
        enable = false
        [params.page.header.number.format]
          h2 = "{h2} {title}"
          h3 = "{h2}.{h3} {title}"
          h4 = "{h2}.{h3}.{h4} {title}"
          h5 = "{h2}.{h3}.{h4}.{h5} {title}"
          h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"

    #  Third-party library config
    [params.page.library]
      [params.page.library.css]
        [params.page.library.css.atkinsonHyperlegibleCSS]
          src = "atkinson-hyperlegible/atkinson-hyperlegible.css"
          defer = true

      [params.page.library.js]
        # someJavaScript = "some.js"
        [params.page.library.js.buttons]
          src = "js/buttons.js"
          defer = true
          async = true
          attr = "github_buttons"

    [params.page.share]
      enable = true
      Twitter = true
      Mastodon = true
      Facebook = false
      Linkedin = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = true
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = true
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

  # Footer config
  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    since = 2010

  [params.HugoShortcodes.Github]
    User = 'Artexxx'
    Repository = 'Artexxx.github.io'

  [params.seo]
    # image = "/apple-touch-icon.png"
    # thumbnailUrl = "/apple-touch-icon.png"

  # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # theme change mode ("switch", "select")
    themeChangeMode = "switch"
    # DoIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      # logo = "/logo.svg"
      # title name
      name = "Artexxx blog"
      # # you can add extra information before the name (HTML format is supported), such as icons
      # pre = ""
      # # you can add extra information after the name (HTML format is supported), such as icons
      # post = ""
      # DoIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

  # TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 50
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "_"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  [params.analytics]
    enable = false

  # Social config about the author
  [params.social]
    GitHub = "Artexxx"
    Twitter = "Artexxx"
    Linkedin = "Artexxx"
    Goodreads = "Artexxx"
    # Lastfm = "sammcj2000"
    Hackernews = "Artexxx"
    Gitlab = "Artexxx"
  [params.social.Mastodon]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 0
    # your social ID
    id = "@Artexxx"
    # prefix of your social link
    prefix = "https://aus.social/"
    # content hovering on the icon
    title = "Mastodon"

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    style = "dracula"
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true

  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

# Author config
[author]
  name = "Artexxx"
  link = "https://www.linkedin.com/in/Artexxx/"
  avatar = "/apple-touch-icon.png"
  gravatarEmail = ""

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = "/:year/:month/:title"
  category = "/blog/category/:slug/"
#
# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  # privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  # taxonomyTerm = ["HTML"]

# Options for taxonomies
[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  series = "series"


